routes/web.php
<?php

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/

Auth::routes(['verify' => true]);

Route::get('/', 'HomeController@index')->name('index');


Route::group(['prefix' => 'admin', 'as' => 'admin::'], function () {

    Route::get('/', 'AdminController@index')->name('index');

    Route::group(['prefix' => 'add', 'as' => 'add.'], function () {
        Route::post('/partner', 'AdminController@add_partner')->name('partner');
    });
});

/* Group routs for partners */
Route::group(['prefix' => 'partner', 'as' => 'partner::'], function () {
    Route::group(['prefix' => '{user}', 'as' => 'current.'], function () {

        Route::get('/', 'PartnerController@index')->name('index');
        Route::patch('/', 'PartnerController@update')->name('update');
        Route::delete('/', 'PartnerController@delete')->name('delete');
        Route::get('/email', 'PartnerController@sendEmailReminder')->name('email');

        Route::group(['prefix' => 'data', 'as' => 'data.'], function () {
            Route::post('/', 'AdminController@updateData')->name('update');
            Route::get('/csv', 'PartnerController@csv')->name('csv');
        });

    });
});


Auth::routes();

Route::group(['prefix' => 'preview', 'as' => 'preview.'], function (){
    Route::group(['prefix' => 'alert', 'as' => 'alert.'], function () {
        Route::get('/{message}/{time}/{redirect_to?}', 'PreviewController@index')->name('message')
            ->where(['time' => '[0-9]+', 'redirect_to' => '[a-z]+']);;
    });
});

Route::get('/home', 'HomeController@index')->name('home');

app/Http/Controllers/AdminController.php
<?php

namespace App\Http\Controllers;

use App\User;
use App\Role;
use App\Notifications\CreateUser;
use App\Notifications\UpdateData;
use App\Factorys\DataFactoryUpload;

use Illuminate\Http\Request;
use Illuminate\Support\Facades\Notification;

class AdminController extends Controller
{
    /**
     * Create a new controller instance.
     *
     * @return void
     */
    public function __construct()
    {
        $this->middleware('auth');
        $this->middleware('is_admin');
    }

    /**
     * Show the application dashboard for admin.
     *
     * @param Request $request
     * @return \Illuminate\Contracts\View\Factory|\Illuminate\View\View
     */
    public function index(Request $request)
    {
        $users = User::with('last_note')->withCount('accounts')->get()->except(\Auth::id());

        return view('admin.main')->with('users',$users);
    }

    /**
     * @param Request $request
     * @return \Illuminate\Http\JsonResponse
     * @throws \Illuminate\Validation\ValidationException
     */
    public function add_partner(Request $request){

        // validator ony for paginate
        $this->validate($request, [
            'name'      => ['required','string','min:3','max:25'],
            'email'     => ['required','email','unique:users,email'],
            'password'  => ['required', 'min:6', 'regex:/^.*(?=.{3,})(?=.*[a-zA-Z])(?=.*[0-9])(?=.*[\d\X]).*$/']
        ]);

        $data = $request->only(['name', 'email', 'password']);

        $_password = $data['password'];
        $data['password'] = bcrypt($data['password']);

        $user = User::create($data);
        $role_employee = Role::where('name', 'partner')->first();
        $user->roles()->attach($role_employee);

        $data['password'] =  $_password;
        Notification::send($user, new CreateUser($user, $data));

        return response()->json([
            'success' => true,
            'message' => 'Create partner successful',
            'data'=>$user], 200);
    }

    /**
     * @param Request $request
     * @param User $user
     * @return \Illuminate\Http\JsonResponse
     * @throws \Exception
     */
    public function updateData(Request $request, User $user){

        $request->validate([
            'commission'=>['required','integer', 'min:0'],
            'accounts'  =>['required','integer', 'min:0'],
            'file'      =>['nullable','mimes:csv,txt'],
        ]);

        $factory = new DataFactoryUpload();
        $factory->upload($request, $user);

        Notification::send($user, new UpdateData($user));

        $user = User::with('last_note')->withCount('accounts')->find($user->id);

        return response()->json(['success' => true,'message'=>'You have successfully update data.','data'=>$user] ,200);
    }
}

resources/views/admin/header.blade.php
<header class=" navbar-expand-md main-header">
    <div class="container">
        @include('layouts.logo')
        <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="{{ __('Toggle navigation') }}">
            <span class="navbar-toggler-icon"></span>
        </button>

        <div class="collapse navbar-collapse" id="navbarSupportedContent">
            <!-- Left Side Of Navbar -->
            <ul class="navbar-nav mr-auto">

            </ul>

            <!-- Right Side Of Navbar -->
            <ul class="nav">
                <!-- Authentication Links -->
                @guest
                    <li class="nav-item">
                        <a class="nav-link" href="{{ route('login') }}">{{ __('Login') }}</a>
                    </li>

                @else
                    <li class="nav-item">
                         <a class="dropdown-item" href="{{ route('logout') }}"
                               onclick="event.preventDefault();
                               document.getElementById('logout-form').submit();">
                                {{ __('Logout') }}
                            </a>

                            <form id="logout-form" action="{{ route('logout') }}" method="POST" style="display: none;">
                                @csrf
                            </form>
                    </li>
                @endguest
            </ul>
        </div>
    </div>
</header>

resources/views/admin/main.blade.php
@extends('layouts.app')

@section('role', 'Admin')

@section('header')
    @include('admin.header')
@endsection

@section('content')
    <main>
        <section class="admin-main">
            <div class="container">
                <div class="row">
                    <div class="col-sm">
                        @include('forms.partner_add')
                    </div>
                    <div class="col-sm-8">
                        @include('admin.partner_list')
                    </div>
                </div>
            </div>
        </section>
    </main>
@endsection

@include('forms.partner_setting')
@include('forms.partner_update')

resources/views/admin/partner_list.blade.php
<div class="box">
    <table class="table table-striped" id="table-partners">
        <thead>
        <tr>
            <th>Partner</th>
            <th>Email Address</th>
            <th># of Accounts</th>
            <th>Last Updated</th>
            <th class="table-actions">Action</th>
        </tr>
        </thead>
        <tbody>
        @foreach($users as $user)
            <tr id="user_{{$user->id}}" data-id="{{$user->id}}">
                <td>
                    <a class="name" href="{{route('partner::current.index', [$user->id])}}"> {{$user->name}} </a>
                </td>
                <td>
                    <span class="email">{{$user->email}}</span>
                </td>
                <td>
                    <span class="accounts">{{ $user->accounts_count }}</span>
                </td>
                <td>
                    <span class="updated_at">{{!empty($user->last_note) ? $user->last_note->created_at : '-'}}</span>
                </td>
                <td class="table-actions">
                    <a class="partner-update"   data-toggle="modal" data-target="#modal-partner-update" href="#">Update</a>
                    <a class="partner-settings" data-toggle="modal" data-target="#modal-partner-settings" href="#">Settings</a>
                    <a class="partner-delete"   data-toggle="modal" data-target="#partner-delete" href="{{ $user->link }}"><i class="fas fa-times"></i></a>
                </td>
            </tr>
        @endforeach


        </tbody>
    </table>

</div>

@push('scripts')
    <script src="{{ asset('js/partner_list.js') }}"></script>
@endpush